apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  labels: 
    name: mysql-pod
    context: docker-k8s-lab
spec: 
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
      name: mysql
  selector: 
    name: mysql-pod
    context: docker-k8s-lab
